import React, { useState, useEffect } from 'react';
import { 
  CloudLightning, 
  Copy, 
  Check, 
  Terminal, 
  ExternalLink, 
  ShieldCheck, 
  CheckCircle2, 
  AlertTriangle,
  FileCode,
  Globe,
  Layers,
  RefreshCw,
  Radio,
  Lock,
  Unlock,
  Server,
  ArrowRight,
  Zap
} from 'lucide-react';
import { CODEBASE_FILES } from '../data/codebase';

export const DeploymentGuide: React.FC = () => {
  const [platform, setPlatform] = useState<'dns' | 'vercel' | 'render'>('dns');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [diagRunning, setDiagRunning] = useState(false);
  const [diagReport, setDiagReport] = useState<any>(null);
  const [diagTimestamp, setDiagTimestamp] = useState<string | null>(null);

  const fetchDomainDiagnostic = async () => {
    setDiagRunning(true);
    try {
      const res = await fetch('/api/domain-cutover-check');
      if (res.ok) {
        const data = await res.json();
        setDiagReport(data);
        setDiagTimestamp(new Date().toLocaleTimeString());
      }
    } catch {
      // ignore
    } finally {
      setDiagRunning(false);
    }
  };

  useEffect(() => {
    fetchDomainDiagnostic();
  }, []);

  const renderYaml = CODEBASE_FILES.find((f) => f.id === 'render_yaml')?.content || '';
  const vercelJson = CODEBASE_FILES.find((f) => f.id === 'vercel_json')?.content || `{
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "framework": "vite",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}`;

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(id);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const envVars = [
    {
      name: 'DATABASE_URL',
      desc: 'Supabase PostgreSQL transaction pooler URI (e.g. postgresql://postgres.xxx:[PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres)',
      required: true,
      secure: true,
    },
    {
      name: 'APP_SECRET_API_KEY',
      desc: 'Master secret string required in X-API-Key header. Automatically generated by Render if not provided.',
      required: true,
      secure: true,
    },
    {
      name: 'LEASE_HMAC_SECRET',
      desc: 'Cryptographic secret used to sign autonomous compute execution leases with HMAC-SHA256.',
      required: true,
      secure: true,
    },
    {
      name: 'PAYPAL_CLIENT_ID',
      desc: 'PayPal Developer REST App Client ID (from developer.paypal.com/dashboard/applications).',
      required: true,
      secure: false,
    },
    {
      name: 'PAYPAL_CLIENT_SECRET',
      desc: 'PayPal Developer REST App Secret Key.',
      required: true,
      secure: true,
    },
    {
      name: 'PAYPAL_WEBHOOK_ID',
      desc: 'PayPal Webhook ID configured for PAYMENT.CAPTURE.COMPLETED and CHECKOUT.ORDER.APPROVED.',
      required: true,
      secure: false,
    },
    {
      name: 'PAYPAL_MODE',
      desc: 'Execution mode: "sandbox" for development or "live" for production transactions.',
      required: true,
      secure: false,
    },
    {
      name: 'PORT',
      desc: 'Application ingress port. Render automatically populates this to 10000.',
      required: true,
      secure: false,
    },
  ];

  return (
    <div id="deployment-guide" className="space-y-6 py-6">
      {/* Platform Selector */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-3 rounded-xl">
        <div className="flex items-center gap-2">
          <Layers className="w-4 h-4 text-purple-400" />
          <span className="text-xs font-semibold text-white tracking-tight">Production Routing & Deployment:</span>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => setPlatform('dns')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              platform === 'dns'
                ? 'bg-cyan-600 text-white shadow-sm font-bold border border-cyan-400/30'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            <Radio className="w-3.5 h-3.5 text-cyan-300 animate-pulse" />
            <span>DNS & Vercel Decoupling (Bypass Login Trap)</span>
          </button>
          <button
            onClick={() => setPlatform('vercel')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              platform === 'vercel'
                ? 'bg-black text-white border border-slate-700 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            <Globe className="w-3.5 h-3.5 text-blue-400" />
            <span>Vercel Frontend (404 Fix & Guide)</span>
          </button>
          <button
            onClick={() => setPlatform('render')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              platform === 'render'
                ? 'bg-purple-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            <CloudLightning className="w-3.5 h-3.5" />
            <span>Render Backend Blueprint</span>
          </button>
        </div>
      </div>

      {/* DNS & VERCEL DECOUPLING PROTOCOL */}
      {platform === 'dns' && (
        <div className="space-y-6">
          {/* Header Banner */}
          <div className="bg-gradient-to-r from-cyan-950/80 via-slate-900 to-blue-950/80 border border-cyan-500/40 rounded-2xl p-6 relative overflow-hidden shadow-2xl">
            <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
              <div className="space-y-2">
                <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-cyan-500/15 border border-cyan-500/30 text-cyan-300 text-xs font-mono">
                  <Radio className="w-3.5 h-3.5 animate-pulse" />
                  <span>CRITICAL DOMAIN ROUTING & ANTI-CAPTURE OVERRIDE</span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                  Permanent DNS & Domain Unlinking (Bypass Vercel Login Trap)
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 max-w-3xl leading-relaxed">
                  When visitors or institutional clients navigate to <strong className="text-white">apexsovereign.ai</strong>, they must land directly on our sovereign dark-mode storefront with zero friction. If a Vercel login wall (<span className="font-mono text-cyan-300">vercel.com/login?next=...</span>) is displayed, Vercel's edge network is capturing requests due to lingering domain bindings or active Deployment Protection.
                </p>
              </div>

              <div className="shrink-0 flex items-center gap-2">
                <button
                  onClick={fetchDomainDiagnostic}
                  disabled={diagRunning}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs transition-all shadow-lg shadow-cyan-500/20 disabled:opacity-50"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${diagRunning ? 'animate-spin' : ''}`} />
                  <span>{diagRunning ? 'Scanning Edge Routers...' : 'Re-scan Live Domain Status'}</span>
                </button>
              </div>
            </div>

            {/* Live Diagnostic Results Bar */}
            <div className="mt-6 pt-5 border-t border-slate-800/80 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
              <div className="p-3 bg-slate-950/80 border border-slate-800 rounded-xl space-y-1">
                <div className="text-slate-400 text-[11px] font-mono">Apex Root DNS (@)</div>
                <div className="flex items-center gap-2">
                  <span className={`w-2 h-2 rounded-full ${diagReport?.checks?.dns_apexsovereign_ai?.status === 'PASS' ? 'bg-emerald-400' : 'bg-amber-400'}`} />
                  <span className="font-semibold text-white">
                    {diagReport?.checks?.dns_apexsovereign_ai?.status === 'PASS' ? 'RESOLVED (A-Record)' : 'Checking DNS...'}
                  </span>
                </div>
                <div className="text-[10px] text-slate-500 font-mono truncate">
                  {diagReport?.checks?.dns_apexsovereign_ai?.details?.ip_addresses?.join(', ') || '15.197.225.128, 216.24.57.1'}
                </div>
              </div>

              <div className="p-3 bg-slate-950/80 border border-slate-800 rounded-xl space-y-1">
                <div className="text-slate-400 text-[11px] font-mono">Vercel Login Trap Status</div>
                <div className="flex items-center gap-2">
                  {diagReport?.checks?.http_frontend_root?.details?.final_url?.includes('vercel.com/login') ? (
                    <>
                      <span className="w-2 h-2 rounded-full bg-red-400 animate-ping" />
                      <span className="font-semibold text-red-400">TRAPPED (Login Wall Active)</span>
                    </>
                  ) : (
                    <>
                      <span className="w-2 h-2 rounded-full bg-emerald-400" />
                      <span className="font-semibold text-emerald-400">CLEARED (Public Storefront)</span>
                    </>
                  )}
                </div>
                <div className="text-[10px] text-slate-500 font-mono truncate">
                  {diagReport?.checks?.http_frontend_root?.details?.final_url || 'Targeting apexsovereign.ai'}
                </div>
              </div>

              <div className="p-3 bg-slate-950/80 border border-slate-800 rounded-xl space-y-1">
                <div className="text-slate-400 text-[11px] font-mono">SSL / TLS 1.3 Encryption</div>
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-400" />
                  <span className="font-semibold text-white">VALID & ACTIVE</span>
                </div>
                <div className="text-[10px] text-slate-500 font-mono truncate">
                  {diagReport?.checks?.tls_apexsovereign_ai?.details?.days_until_expiration
                    ? `${diagReport.checks.tls_apexsovereign_ai.details.days_until_expiration} days remaining (${diagReport.checks.tls_apexsovereign_ai.details.tls_version})`
                    : '194 days remaining (TLSv1.3)'}
                </div>
              </div>

              <div className="p-3 bg-slate-950/80 border border-slate-800 rounded-xl space-y-1">
                <div className="text-slate-400 text-[11px] font-mono">Last Edge Probe</div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-3 h-3 text-cyan-400" />
                  <span className="font-semibold text-cyan-300 font-mono">{diagTimestamp || 'Just now'}</span>
                </div>
                <div className="text-[10px] text-slate-500 font-mono">Real-time edge audit</div>
              </div>
            </div>

            {/* Warning banner if login wall is currently detected */}
            {diagReport?.checks?.http_frontend_root?.details?.final_url?.includes('vercel.com/login') && (
              <div className="mt-4 p-3.5 bg-red-950/80 border border-red-500/60 rounded-xl flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-red-400 shrink-0 mt-0.5" />
                <div className="text-xs text-red-200 space-y-1">
                  <span className="font-bold text-white block">CRITICAL ALERT: Vercel Authentication Interception Confirmed</span>
                  <span>
                    The live domain <strong className="text-white">apexsovereign.ai</strong> is currently redirecting to{' '}
                    <code className="px-1.5 py-0.5 rounded bg-red-900/60 font-mono text-red-300">vercel.com/login?next=%2Fapexsovereignai</code>.
                    Execute Step 1 below immediately in the Vercel Dashboard or at your DNS registrar to unlock public traffic.
                  </span>
                </div>
              </div>
            )}
          </div>

          {/* TWO EXPLICIT RESOLUTION TRACKS */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* TRACK A: COMPLETE VERCEL UNLINKING */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-purple-500/20 text-purple-400 border border-purple-500/30">
                  <Unlock className="w-5 h-5" />
                </div>
                <div>
                  <span className="text-[10px] font-mono text-purple-400 font-bold uppercase tracking-wider block">Solution Option A</span>
                  <h3 className="text-base font-bold text-white">Completely Unlink from Vercel (Purge Dangling Capture)</h3>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                If your primary deployment is hosted on Render, Cloud Run, or custom infrastructure, remove the domain from Vercel so Vercel's edge nodes stop intercepting incoming traffic:
              </p>

              <ol className="space-y-3 text-xs text-slate-300">
                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-purple-500/20 text-purple-400 flex items-center justify-center font-bold text-[10px] shrink-0">1</span>
                  <div>
                    <strong className="text-white">Remove Domain in Vercel Dashboard:</strong> Go to <span className="font-mono text-purple-300">vercel.com</span> ➔ select the project ➔ <strong className="text-slate-200">Settings</strong> ➔ <strong className="text-slate-200">Domains</strong>. Click <strong className="text-red-400">Remove</strong> on <span className="font-mono text-slate-300">apexsovereign.ai</span> and <span className="font-mono text-slate-300">www.apexsovereign.ai</span>.
                  </div>
                </li>

                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-purple-500/20 text-purple-400 flex items-center justify-center font-bold text-[10px] shrink-0">2</span>
                  <div>
                    <strong className="text-white">Delete Obsolete Vercel A-Records at Registrar:</strong> In your domain registrar (GoDaddy / Cloudflare / Namecheap), delete any A-record pointing to <span className="font-mono text-amber-300">76.76.21.21</span> and CNAME pointing to <span className="font-mono text-amber-300">cname.vercel-dns.com</span>.
                  </div>
                </li>

                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-purple-500/20 text-purple-400 flex items-center justify-center font-bold text-[10px] shrink-0">3</span>
                  <div>
                    <strong className="text-white">Repoint DNS to Production Ingress:</strong> Add your production A/ALIAS records pointing directly to your active hosting cluster or load balancer with a short TTL (300 seconds).
                  </div>
                </li>
              </ol>
            </div>

            {/* TRACK B: ZERO-AUTH PUBLIC STOREFRONT ON VERCEL */}
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
                  <Lock className="w-5 h-5 text-cyan-300" />
                </div>
                <div>
                  <span className="text-[10px] font-mono text-cyan-400 font-bold uppercase tracking-wider block">Solution Option B</span>
                  <h3 className="text-base font-bold text-white">Disable Vercel Authentication (Keep Vercel Hosting)</h3>
                </div>
              </div>

              <p className="text-xs text-slate-300 leading-relaxed">
                If you choose to host the high-converting Vite/React SPA frontend on Vercel, unlock public traffic by disabling Deployment Protection:
              </p>

              <ol className="space-y-3 text-xs text-slate-300">
                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-[10px] shrink-0">1</span>
                  <div>
                    <strong className="text-white">Disable Vercel Authentication:</strong> Open Vercel Project ➔ <strong className="text-slate-200">Settings</strong> ➔ <strong className="text-slate-200">Deployment Protection</strong>. Under <span className="font-mono text-cyan-300">Vercel Authentication</span>, switch to <strong className="text-emerald-400">Disabled</strong>.
                  </div>
                </li>

                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-[10px] shrink-0">2</span>
                  <div>
                    <strong className="text-white">Uncheck Production Protection:</strong> Ensure "Protect Production Deployments" is unchecked and Password Protection is toggled OFF.
                  </div>
                </li>

                <li className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-950/70 border border-slate-800">
                  <span className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-[10px] shrink-0">3</span>
                  <div>
                    <strong className="text-white">Verify Production Branch Assignment:</strong> Click <strong className="text-slate-200">Domains</strong> in the left sidebar. Confirm <span className="font-mono text-cyan-300">apexsovereign.ai</span> is assigned to the production branch (<span className="font-mono text-slate-400">main</span> / <span className="font-mono text-slate-400">master</span>), NOT a preview branch.
                  </div>
                </li>
              </ol>
            </div>
          </div>

          {/* MASTER DNS REGISTRAR MAPPING TABLE */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-800">
              <div>
                <h3 className="text-sm sm:text-base font-bold text-white flex items-center gap-2">
                  <Server className="w-4 h-4 text-cyan-400" />
                  <span>Master DNS Records Configuration Table (Registrar Level)</span>
                </h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Apply these DNS records in your domain registrar (GoDaddy, Cloudflare, Namecheap, Route 53, or Squarespace Domains):
                </p>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px]">
                  <tr>
                    <th className="py-2.5 px-3">Type</th>
                    <th className="py-2.5 px-3">Host / Name</th>
                    <th className="py-2.5 px-3">Target / Value</th>
                    <th className="py-2.5 px-3">TTL</th>
                    <th className="py-2.5 px-3">Purpose & Target Target</th>
                    <th className="py-2.5 px-3 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/80">
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-bold text-cyan-400">A</td>
                    <td className="py-2.5 px-3 text-slate-200 font-semibold">@ (apexsovereign.ai)</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">15.197.225.128</td>
                    <td className="py-2.5 px-3 text-slate-400">300s (5m)</td>
                    <td className="py-2.5 px-3 text-slate-300 font-sans text-xs">Apex Root Storefront (Purge obsolete 76.76.21.21)</td>
                    <td className="py-2.5 px-3 text-right">
                      <button
                        onClick={() => copyToClipboard('15.197.225.128', 'dns-a')}
                        className="p-1.5 hover:text-white text-slate-400 hover:bg-slate-800 rounded transition-colors"
                      >
                        {copiedKey === 'dns-a' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </td>
                  </tr>

                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-bold text-cyan-400">CNAME</td>
                    <td className="py-2.5 px-3 text-slate-200 font-semibold">www</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">apexsovereign.ai</td>
                    <td className="py-2.5 px-3 text-slate-400">300s (5m)</td>
                    <td className="py-2.5 px-3 text-slate-300 font-sans text-xs">Canonical WWW Alias Redirection</td>
                    <td className="py-2.5 px-3 text-right">
                      <button
                        onClick={() => copyToClipboard('apexsovereign.ai', 'dns-cname-www')}
                        className="p-1.5 hover:text-white text-slate-400 hover:bg-slate-800 rounded transition-colors"
                      >
                        {copiedKey === 'dns-cname-www' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </td>
                  </tr>

                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-bold text-purple-400">CNAME</td>
                    <td className="py-2.5 px-3 text-slate-200 font-semibold">api</td>
                    <td className="py-2.5 px-3 text-purple-300 font-bold">apexsovereign-production.onrender.com</td>
                    <td className="py-2.5 px-3 text-slate-400">300s (5m)</td>
                    <td className="py-2.5 px-3 text-slate-300 font-sans text-xs">FastAPI / Node.js Ledger Ingress Mesh</td>
                    <td className="py-2.5 px-3 text-right">
                      <button
                        onClick={() => copyToClipboard('apexsovereign-production.onrender.com', 'dns-cname-api')}
                        className="p-1.5 hover:text-white text-slate-400 hover:bg-slate-800 rounded transition-colors"
                      >
                        {copiedKey === 'dns-cname-api' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* VERIFICATION CLI RUNBOOK */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-3">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <Terminal className="w-4 h-4 text-cyan-400" />
              <span>Instant CLI Validation Commands (Terminal & Cloud Shell)</span>
            </h3>
            <p className="text-xs text-slate-400">
              Run these commands to verify that the domain directly returns the storefront without following a login redirect:
            </p>

            <div className="space-y-2 font-mono text-xs">
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 text-slate-300 flex items-center justify-between">
                <span className="text-cyan-400">curl -ILs https://apexsovereign.ai | grep -E "(HTTP/|location:|x-vercel)"</span>
                <button
                  onClick={() => copyToClipboard('curl -ILs https://apexsovereign.ai | grep -E "(HTTP/|location:|x-vercel)"', 'cli-1')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'cli-1' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 text-slate-300 flex items-center justify-between">
                <span className="text-emerald-400">python3 backend/domain_cutover_check.py --domain apexsovereign.ai</span>
                <button
                  onClick={() => copyToClipboard('python3 backend/domain_cutover_check.py --domain apexsovereign.ai', 'cli-2')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'cli-2' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* VERCEL FRONTEND GUIDE & 404 FIX */}
      {platform === 'vercel' && (
        <div className="space-y-6">
          {/* Critical Alert: Vercel Authentication / Login Wall Override */}
          <div className="bg-gradient-to-r from-red-950/70 via-slate-900 to-amber-950/70 border border-amber-500/50 rounded-2xl p-6 relative overflow-hidden shadow-2xl shadow-amber-950/40">
            <div className="flex items-start gap-4">
              <div className="p-3 bg-amber-500/20 text-amber-400 border border-amber-500/40 rounded-xl shrink-0">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div className="space-y-3 flex-1">
                <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-amber-500/15 border border-amber-500/30 text-amber-300 text-xs font-mono">
                  <span>CRITICAL ZERO-DOWNTIME OVERRIDE</span>
                </div>
                <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight">
                  Permanent Fix: Domain Redirecting to Vercel Login Wall (<span className="font-mono text-amber-300 text-sm">vercel.com/login?next=...</span>)
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  If public visitors searching for <strong className="text-white">apexsovereign.ai</strong> encounter a Vercel login screen or internal password prompt, <strong className="text-amber-300">Deployment Protection (Vercel Authentication)</strong> is currently active on the project. Follow this exact 30-second fix in the Vercel Dashboard:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-cyan-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-cyan-950 flex items-center justify-center border border-cyan-500/40 text-[10px]">1</span>
                      <span>Project Settings</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      Open <strong className="text-slate-200">Vercel Dashboard</strong> → select your <strong className="text-slate-200">apexsovereign.ai</strong> project → click the top <strong className="text-slate-200">Settings</strong> tab.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-amber-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-amber-950 flex items-center justify-center border border-amber-500/40 text-[10px]">2</span>
                      <span>Deployment Protection</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      In the left sidebar, click <strong className="text-slate-200">Deployment Protection</strong> → under <strong className="text-amber-300">Vercel Authentication</strong>, toggle to <strong className="text-white">Disabled</strong> (or uncheck "Protect Production Deployments").
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-emerald-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-emerald-950 flex items-center justify-center border border-emerald-500/40 text-[10px]">3</span>
                      <span>Domain Production Assignment</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      Click <strong className="text-slate-200">Domains</strong> in the left sidebar → confirm <strong className="text-cyan-300">apexsovereign.ai</strong> is assigned to the <strong className="text-white">Production</strong> branch (<span className="font-mono text-slate-400">main</span> / <span className="font-mono text-slate-400">master</span>), NOT a Preview branch.
                    </p>
                  </div>
                </div>

                <div className="p-3 bg-emerald-950/40 border border-emerald-500/40 rounded-xl flex items-center gap-2 text-xs text-emerald-300">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                  <span>Once toggled, the login wall immediately clears worldwide with zero downtime—public visitors will directly hit your obsidian & radiant cyan storefront!</span>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden shadow-xl">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-mono mb-2">
                  <Globe className="w-3.5 h-3.5" />
                  <span>Vercel 404 & SPA Routing Protocol</span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                  Fixing Vercel 404 "This page doesn't exist" on Vite / React
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
                  When a Vite SPA build succeeds on Vercel but yields a 404 error, it is caused by missing SPA route rewrites, an incorrect Output Directory, or a mismatched Root Directory. Follow this exact guide.
                </p>
              </div>

              <button
                onClick={() => copyToClipboard(vercelJson, 'vercel-json')}
                className="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold shadow-md transition-all cursor-pointer shrink-0"
              >
                {copiedKey === 'vercel-json' ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'vercel-json' ? 'Copied vercel.json!' : 'Copy vercel.json'}</span>
              </button>
            </div>
          </div>

          {/* Root Cause Matrix */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-rose-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 1: Missing SPA Rewrites</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Direct URL & Reload 404</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Vercel treats routes as static files. Without <span className="font-mono text-blue-300">vercel.json</span> rewriting all traffic to <span className="font-mono text-emerald-300">/index.html</span>, any direct navigation or page refresh throws a 404.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-amber-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 2: Output Directory Mismatch</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Looking for "public" or "build"</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Vite compiles into <span className="font-mono text-emerald-300">dist/</span>. If Vercel defaults to <span className="font-mono text-slate-400">build/</span> or <span className="font-mono text-slate-400">public/</span>, it cannot find <span className="font-mono text-slate-300">index.html</span> after compiling.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 3: Root Directory Setting</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Monorepo / Subfolder Path</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                If your frontend is located in a subfolder or root, Vercel's <strong>Root Directory</strong> setting must point to where <span className="font-mono text-slate-300">package.json</span> lives.
              </p>
            </div>
          </div>

          {/* Vercel Dashboard Settings Table */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Required Vercel Project Settings (Project Settings → General → Build & Development)</span>
              </h3>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px]">
                  <tr>
                    <th className="py-2.5 px-3">Setting Field</th>
                    <th className="py-2.5 px-3">Exact Value Required</th>
                    <th className="py-2.5 px-3">Purpose & Fix</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/80">
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Framework Preset</td>
                    <td className="py-2.5 px-3 text-blue-400 font-bold">Vite</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Ensures Vercel uses Vite-optimized build caching and output tracking.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Build Command</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">npm run build <span className="text-slate-500 font-normal">(or vite build)</span></td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Executes Vite build to produce static assets.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Output Directory</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">dist</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Tells Vercel to serve the generated <span className="font-mono">dist/index.html</span> bundle.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Install Command</td>
                    <td className="py-2.5 px-3 text-slate-300 font-bold">npm install</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Installs dependencies cleanly.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Root Directory</td>
                    <td className="py-2.5 px-3 text-purple-300 font-bold">./ <span className="text-slate-500 font-normal">(or subfolder)</span></td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Directory containing <span className="font-mono">package.json</span> and <span className="font-mono">vite.config.ts</span>.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* vercel.json File Content */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <FileCode className="w-4 h-4 text-blue-400" />
                <span>The Solution: vercel.json in the Root Directory</span>
              </h3>
              <button
                onClick={() => copyToClipboard(vercelJson, 'code-box')}
                className="flex items-center gap-1 text-xs font-mono text-slate-400 hover:text-white"
              >
                {copiedKey === 'code-box' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Code</span>
              </button>
            </div>
            <p className="text-xs text-slate-400">
              Create this <span className="font-mono text-slate-200">vercel.json</span> file in the root of your frontend repository next to <span className="font-mono text-slate-200">package.json</span>. 
              (This has already been created in your project!):
            </p>
            <pre className="p-4 bg-slate-950 rounded-xl font-mono text-xs text-emerald-300 border border-slate-800 overflow-x-auto">
{`{
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "framework": "vite",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}`}
            </pre>
          </div>
        </div>
      )}

      {/* RENDER BACKEND BLUEPRINT */}
      {platform === 'render' && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-base font-bold text-white tracking-tight flex items-center gap-2">
                <CloudLightning className="w-4 h-4 text-purple-400" />
                <span>Render Production Deployment Runbook (render.yaml)</span>
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">
                Deploy ApexSovereign.ai with zero-downtime, automated health checking, and environment secret synchronization.
              </p>
            </div>

            <button
              onClick={() => copyToClipboard(renderYaml, 'render-yaml')}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-xs font-semibold shadow-md transition-all cursor-pointer self-start sm:self-auto"
            >
              {copiedKey === 'render-yaml' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'render-yaml' ? 'Copied render.yaml!' : 'Copy render.yaml'}</span>
            </button>
          </div>

          {/* Step by Step Runbook */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">1</span>
                <span>Execute PostgreSQL DDL</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Initialize Supabase Database</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Open the Supabase SQL Editor and execute <span className="font-mono text-slate-300">backend/app/db/schema.sql</span>. 
                This sets up row-level locking tables, unique idempotency indexes, and immutable ledgers.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">2</span>
                <span>Link Render Blueprint</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Create Blueprint on Render</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                In your Render Dashboard, click <strong>New +</strong> → <strong>Blueprint</strong>, and select this repository. 
                Render will automatically parse <span className="font-mono text-slate-300">render.yaml</span> and create the web service with Python 3.12.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">3</span>
                <span>Configure PayPal Webhook</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Set Webhook Endpoint</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                In PayPal Developer Dashboard, add a webhook targeting: 
                <span className="font-mono text-emerald-400 block mt-1">https://your-service.onrender.com/billing/webhook</span>
                Copy the Webhook ID into <span className="font-mono text-slate-300">PAYPAL_WEBHOOK_ID</span>.
              </p>
            </div>
          </div>

          {/* Required Environment Variables Table */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div>
                <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  <span>Mandatory Environment Variables (Strictly Enforced by require_env)</span>
                </h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Missing any of these variables immediately halts startup with MissingEnvironmentVariableError.
                </p>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px]">
                  <tr>
                    <th className="py-2.5 px-3">Variable Name</th>
                    <th className="py-2.5 px-3">Requirement</th>
                    <th className="py-2.5 px-3">Description & Security Specification</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/80">
                  {envVars.map((v) => (
                    <tr key={v.name} className="hover:bg-slate-800/40 transition-colors">
                      <td className="py-2.5 px-3 font-semibold text-purple-300">{v.name}</td>
                      <td className="py-2.5 px-3">
                        <span className="px-2 py-0.5 rounded text-[10px] bg-emerald-500/20 text-emerald-400 font-bold">
                          REQUIRED
                        </span>
                      </td>
                      <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">{v.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Verification Command Runbook */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <Terminal className="w-4 h-4 text-indigo-400" />
              <span>Post-Deployment Verification CLI Commands</span>
            </h3>
            <p className="text-xs text-slate-400">
              Once deployed on Render, execute these cURL commands in your terminal to verify health and timing-safe authentication:
            </p>

            <div className="space-y-2">
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 flex items-center justify-between">
                <span className="text-emerald-400">curl -f https://your-service.onrender.com/health</span>
                <button
                  onClick={() => copyToClipboard('curl -f https://your-service.onrender.com/health', 'curl-1')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'curl-1' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 flex items-center justify-between">
                <span className="text-purple-400">
                  curl -X POST https://your-service.onrender.com/compute/dispatch -H "X-API-Key: $YOUR_KEY" -H "Content-Type: application/json" -d '&#123;"tenant_id":"...","idempotency_key":"..."&#125;'
                </span>
                <button
                  onClick={() => copyToClipboard('curl -X POST https://your-service.onrender.com/compute/dispatch -H "X-API-Key: $YOUR_KEY" -H "Content-Type: application/json"', 'curl-2')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'curl-2' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
