import React, { useState } from 'react';
import { 
  CloudLightning, 
  Copy, 
  Check, 
  Terminal, 
  ExternalLink, 
  ShieldCheck, 
  CheckCircle2, 
  AlertTriangle,
  FileCode,
  Globe,
  Layers
} from 'lucide-react';
import { CODEBASE_FILES } from '../data/codebase';

export const DeploymentGuide: React.FC = () => {
  const [platform, setPlatform] = useState<'vercel' | 'render'>('vercel');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const renderYaml = CODEBASE_FILES.find((f) => f.id === 'render_yaml')?.content || '';
  const vercelJson = CODEBASE_FILES.find((f) => f.id === 'vercel_json')?.content || `{
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "framework": "vite",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}`;

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(id);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const envVars = [
    {
      name: 'DATABASE_URL',
      desc: 'Supabase PostgreSQL transaction pooler URI (e.g. postgresql://postgres.xxx:[PASSWORD]@aws-0-us-east-1.pooler.supabase.com:6543/postgres)',
      required: true,
      secure: true,
    },
    {
      name: 'APP_SECRET_API_KEY',
      desc: 'Master secret string required in X-API-Key header. Automatically generated by Render if not provided.',
      required: true,
      secure: true,
    },
    {
      name: 'LEASE_HMAC_SECRET',
      desc: 'Cryptographic secret used to sign autonomous compute execution leases with HMAC-SHA256.',
      required: true,
      secure: true,
    },
    {
      name: 'PAYPAL_CLIENT_ID',
      desc: 'PayPal Developer REST App Client ID (from developer.paypal.com/dashboard/applications).',
      required: true,
      secure: false,
    },
    {
      name: 'PAYPAL_CLIENT_SECRET',
      desc: 'PayPal Developer REST App Secret Key.',
      required: true,
      secure: true,
    },
    {
      name: 'PAYPAL_WEBHOOK_ID',
      desc: 'PayPal Webhook ID configured for PAYMENT.CAPTURE.COMPLETED and CHECKOUT.ORDER.APPROVED.',
      required: true,
      secure: false,
    },
    {
      name: 'PAYPAL_MODE',
      desc: 'Execution mode: "sandbox" for development or "live" for production transactions.',
      required: true,
      secure: false,
    },
    {
      name: 'PORT',
      desc: 'Application ingress port. Render automatically populates this to 10000.',
      required: true,
      secure: false,
    },
  ];

  return (
    <div id="deployment-guide" className="space-y-6 py-6">
      {/* Platform Selector */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-3 rounded-xl">
        <div className="flex items-center gap-2">
          <Layers className="w-4 h-4 text-purple-400" />
          <span className="text-xs font-semibold text-white tracking-tight">Production Deployment Target:</span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setPlatform('vercel')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              platform === 'vercel'
                ? 'bg-black text-white border border-slate-700 shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            <Globe className="w-3.5 h-3.5 text-blue-400" />
            <span>Vercel Frontend (404 Fix & Guide)</span>
          </button>
          <button
            onClick={() => setPlatform('render')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              platform === 'render'
                ? 'bg-purple-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            }`}
          >
            <CloudLightning className="w-3.5 h-3.5" />
            <span>Render Backend Blueprint</span>
          </button>
        </div>
      </div>

      {/* VERCEL FRONTEND GUIDE & 404 FIX */}
      {platform === 'vercel' && (
        <div className="space-y-6">
          {/* Critical Alert: Vercel Authentication / Login Wall Override */}
          <div className="bg-gradient-to-r from-red-950/70 via-slate-900 to-amber-950/70 border border-amber-500/50 rounded-2xl p-6 relative overflow-hidden shadow-2xl shadow-amber-950/40">
            <div className="flex items-start gap-4">
              <div className="p-3 bg-amber-500/20 text-amber-400 border border-amber-500/40 rounded-xl shrink-0">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div className="space-y-3 flex-1">
                <div className="inline-flex items-center gap-2 px-2.5 py-0.5 rounded-full bg-amber-500/15 border border-amber-500/30 text-amber-300 text-xs font-mono">
                  <span>CRITICAL ZERO-DOWNTIME OVERRIDE</span>
                </div>
                <h2 className="text-lg sm:text-xl font-bold text-white tracking-tight">
                  Permanent Fix: Domain Redirecting to Vercel Login Wall (<span className="font-mono text-amber-300 text-sm">vercel.com/login?next=...</span>)
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                  If public visitors searching for <strong className="text-white">apexsovereign.ai</strong> encounter a Vercel login screen or internal password prompt, <strong className="text-amber-300">Deployment Protection (Vercel Authentication)</strong> is currently active on the project. Follow this exact 30-second fix in the Vercel Dashboard:
                </p>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-cyan-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-cyan-950 flex items-center justify-center border border-cyan-500/40 text-[10px]">1</span>
                      <span>Project Settings</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      Open <strong className="text-slate-200">Vercel Dashboard</strong> → select your <strong className="text-slate-200">apexsovereign.ai</strong> project → click the top <strong className="text-slate-200">Settings</strong> tab.
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-amber-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-amber-950 flex items-center justify-center border border-amber-500/40 text-[10px]">2</span>
                      <span>Deployment Protection</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      In the left sidebar, click <strong className="text-slate-200">Deployment Protection</strong> → under <strong className="text-amber-300">Vercel Authentication</strong>, toggle to <strong className="text-white">Disabled</strong> (or uncheck "Protect Production Deployments").
                    </p>
                  </div>

                  <div className="p-3.5 bg-slate-950/90 border border-slate-800 rounded-xl space-y-1.5">
                    <div className="text-xs font-mono text-emerald-400 font-bold flex items-center gap-1.5">
                      <span className="w-4 h-4 rounded-full bg-emerald-950 flex items-center justify-center border border-emerald-500/40 text-[10px]">3</span>
                      <span>Domain Production Assignment</span>
                    </div>
                    <p className="text-xs text-slate-400">
                      Click <strong className="text-slate-200">Domains</strong> in the left sidebar → confirm <strong className="text-cyan-300">apexsovereign.ai</strong> is assigned to the <strong className="text-white">Production</strong> branch (<span className="font-mono text-slate-400">main</span> / <span className="font-mono text-slate-400">master</span>), NOT a Preview branch.
                    </p>
                  </div>
                </div>

                <div className="p-3 bg-emerald-950/40 border border-emerald-500/40 rounded-xl flex items-center gap-2 text-xs text-emerald-300">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                  <span>Once toggled, the login wall immediately clears worldwide with zero downtime—public visitors will directly hit your obsidian & radiant cyan storefront!</span>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 relative overflow-hidden shadow-xl">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-mono mb-2">
                  <Globe className="w-3.5 h-3.5" />
                  <span>Vercel 404 & SPA Routing Protocol</span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                  Fixing Vercel 404 "This page doesn't exist" on Vite / React
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
                  When a Vite SPA build succeeds on Vercel but yields a 404 error, it is caused by missing SPA route rewrites, an incorrect Output Directory, or a mismatched Root Directory. Follow this exact guide.
                </p>
              </div>

              <button
                onClick={() => copyToClipboard(vercelJson, 'vercel-json')}
                className="inline-flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-bold shadow-md transition-all cursor-pointer shrink-0"
              >
                {copiedKey === 'vercel-json' ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'vercel-json' ? 'Copied vercel.json!' : 'Copy vercel.json'}</span>
              </button>
            </div>
          </div>

          {/* Root Cause Matrix */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-rose-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 1: Missing SPA Rewrites</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Direct URL & Reload 404</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Vercel treats routes as static files. Without <span className="font-mono text-blue-300">vercel.json</span> rewriting all traffic to <span className="font-mono text-emerald-300">/index.html</span>, any direct navigation or page refresh throws a 404.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-amber-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 2: Output Directory Mismatch</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Looking for "public" or "build"</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Vite compiles into <span className="font-mono text-emerald-300">dist/</span>. If Vercel defaults to <span className="font-mono text-slate-400">build/</span> or <span className="font-mono text-slate-400">public/</span>, it cannot find <span className="font-mono text-slate-300">index.html</span> after compiling.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <AlertTriangle className="w-4 h-4" />
                <span>Issue 3: Root Directory Setting</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Monorepo / Subfolder Path</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                If your frontend is located in a subfolder or root, Vercel's <strong>Root Directory</strong> setting must point to where <span className="font-mono text-slate-300">package.json</span> lives.
              </p>
            </div>
          </div>

          {/* Vercel Dashboard Settings Table */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Required Vercel Project Settings (Project Settings → General → Build & Development)</span>
              </h3>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px]">
                  <tr>
                    <th className="py-2.5 px-3">Setting Field</th>
                    <th className="py-2.5 px-3">Exact Value Required</th>
                    <th className="py-2.5 px-3">Purpose & Fix</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/80">
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Framework Preset</td>
                    <td className="py-2.5 px-3 text-blue-400 font-bold">Vite</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Ensures Vercel uses Vite-optimized build caching and output tracking.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Build Command</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">npm run build <span className="text-slate-500 font-normal">(or vite build)</span></td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Executes Vite build to produce static assets.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Output Directory</td>
                    <td className="py-2.5 px-3 text-emerald-400 font-bold">dist</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Tells Vercel to serve the generated <span className="font-mono">dist/index.html</span> bundle.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Install Command</td>
                    <td className="py-2.5 px-3 text-slate-300 font-bold">npm install</td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Installs dependencies cleanly.</td>
                  </tr>
                  <tr className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-2.5 px-3 font-semibold text-white">Root Directory</td>
                    <td className="py-2.5 px-3 text-purple-300 font-bold">./ <span className="text-slate-500 font-normal">(or subfolder)</span></td>
                    <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">Directory containing <span className="font-mono">package.json</span> and <span className="font-mono">vite.config.ts</span>.</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* vercel.json File Content */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <FileCode className="w-4 h-4 text-blue-400" />
                <span>The Solution: vercel.json in the Root Directory</span>
              </h3>
              <button
                onClick={() => copyToClipboard(vercelJson, 'code-box')}
                className="flex items-center gap-1 text-xs font-mono text-slate-400 hover:text-white"
              >
                {copiedKey === 'code-box' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Code</span>
              </button>
            </div>
            <p className="text-xs text-slate-400">
              Create this <span className="font-mono text-slate-200">vercel.json</span> file in the root of your frontend repository next to <span className="font-mono text-slate-200">package.json</span>. 
              (This has already been created in your project!):
            </p>
            <pre className="p-4 bg-slate-950 rounded-xl font-mono text-xs text-emerald-300 border border-slate-800 overflow-x-auto">
{`{
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "framework": "vite",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/index.html"
    }
  ]
}`}
            </pre>
          </div>
        </div>
      )}

      {/* RENDER BACKEND BLUEPRINT */}
      {platform === 'render' && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-base font-bold text-white tracking-tight flex items-center gap-2">
                <CloudLightning className="w-4 h-4 text-purple-400" />
                <span>Render Production Deployment Runbook (render.yaml)</span>
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">
                Deploy ApexSovereign.ai with zero-downtime, automated health checking, and environment secret synchronization.
              </p>
            </div>

            <button
              onClick={() => copyToClipboard(renderYaml, 'render-yaml')}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-purple-600 hover:bg-purple-500 text-white rounded-lg text-xs font-semibold shadow-md transition-all cursor-pointer self-start sm:self-auto"
            >
              {copiedKey === 'render-yaml' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'render-yaml' ? 'Copied render.yaml!' : 'Copy render.yaml'}</span>
            </button>
          </div>

          {/* Step by Step Runbook */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">1</span>
                <span>Execute PostgreSQL DDL</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Initialize Supabase Database</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Open the Supabase SQL Editor and execute <span className="font-mono text-slate-300">backend/app/db/schema.sql</span>. 
                This sets up row-level locking tables, unique idempotency indexes, and immutable ledgers.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">2</span>
                <span>Link Render Blueprint</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Create Blueprint on Render</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                In your Render Dashboard, click <strong>New +</strong> → <strong>Blueprint</strong>, and select this repository. 
                Render will automatically parse <span className="font-mono text-slate-300">render.yaml</span> and create the web service with Python 3.12.
              </p>
            </div>

            <div className="bg-slate-900 border border-slate-800 p-5 rounded-xl space-y-2">
              <div className="flex items-center gap-2 text-xs font-mono text-purple-400">
                <span className="w-5 h-5 rounded-full bg-purple-500/20 flex items-center justify-center font-bold">3</span>
                <span>Configure PayPal Webhook</span>
              </div>
              <h3 className="text-sm font-semibold text-white">Set Webhook Endpoint</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                In PayPal Developer Dashboard, add a webhook targeting: 
                <span className="font-mono text-emerald-400 block mt-1">https://your-service.onrender.com/billing/webhook</span>
                Copy the Webhook ID into <span className="font-mono text-slate-300">PAYPAL_WEBHOOK_ID</span>.
              </p>
            </div>
          </div>

          {/* Required Environment Variables Table */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div>
                <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  <span>Mandatory Environment Variables (Strictly Enforced by require_env)</span>
                </h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Missing any of these variables immediately halts startup with MissingEnvironmentVariableError.
                </p>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead className="bg-slate-950 text-slate-400 border-b border-slate-800 text-[11px]">
                  <tr>
                    <th className="py-2.5 px-3">Variable Name</th>
                    <th className="py-2.5 px-3">Requirement</th>
                    <th className="py-2.5 px-3">Description & Security Specification</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/80">
                  {envVars.map((v) => (
                    <tr key={v.name} className="hover:bg-slate-800/40 transition-colors">
                      <td className="py-2.5 px-3 font-semibold text-purple-300">{v.name}</td>
                      <td className="py-2.5 px-3">
                        <span className="px-2 py-0.5 rounded text-[10px] bg-emerald-500/20 text-emerald-400 font-bold">
                          REQUIRED
                        </span>
                      </td>
                      <td className="py-2.5 px-3 text-slate-400 font-sans text-xs">{v.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Verification Command Runbook */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-3">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <Terminal className="w-4 h-4 text-indigo-400" />
              <span>Post-Deployment Verification CLI Commands</span>
            </h3>
            <p className="text-xs text-slate-400">
              Once deployed on Render, execute these cURL commands in your terminal to verify health and timing-safe authentication:
            </p>

            <div className="space-y-2">
              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 flex items-center justify-between">
                <span className="text-emerald-400">curl -f https://your-service.onrender.com/health</span>
                <button
                  onClick={() => copyToClipboard('curl -f https://your-service.onrender.com/health', 'curl-1')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'curl-1' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              <div className="bg-slate-950 p-3 rounded-lg border border-slate-800 font-mono text-xs text-slate-300 flex items-center justify-between">
                <span className="text-purple-400">
                  curl -X POST https://your-service.onrender.com/compute/dispatch -H "X-API-Key: $YOUR_KEY" -H "Content-Type: application/json" -d '&#123;"tenant_id":"...","idempotency_key":"..."&#125;'
                </span>
                <button
                  onClick={() => copyToClipboard('curl -X POST https://your-service.onrender.com/compute/dispatch -H "X-API-Key: $YOUR_KEY" -H "Content-Type: application/json"', 'curl-2')}
                  className="p-1 hover:text-white text-slate-500"
                >
                  {copiedKey === 'curl-2' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
